### ISSUE TITLE
请问下，这个可以下载afreecatv直播吗?

### ISSUE THREAD

**Issue by ChenlieShi-NWU** [minimAluminiumalism/AfreecaTVCrawler#1]

**Comment by minimAluminiumalism** [comment]
可以，但这只是一个练手项目，只能下载主播直播完成后存档的视频，AfreecaTV 在中国的访问速度非常慢，我测试后发现即使加入多线程对于下载速度也没有太大提升，这决定了 ts 文件的获取会非常耗时，我建议你在一台国外的 VPS 上运行下载完成后在取回本地。另外请记得在合并为 mp4 文件后手动删除 ts 文件。
你可以提出改进建议。
